GET http://localhost:3001/api/blogs

###

POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Travel to Japan!",
    "author": "Hikari Inaba",
    "url": "http://desuka-travels.com.jp",
    "likes": 0
}

###

DELETE http://localhost:3001/api/blogs/62f0f30a16b0cbdb707204c1

###

PUT http://localhost:3001/api/blogs/62f220e43e6edb6f9acc018a
Content-Type: application/json

{
    "titles": "Travel to Kyoto!"
}

###

POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "Ruka chan",
    "name": "Ruka Inaba",
    "password": "password"
}