GET http://localhost:3001/api/blogs

###

POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Travel to Japan!",
    "author": "Hikari Inaba",
    "url": "http://desuka-travels.com.jp",
    "likes": 0
}